name = "cloudflare-temp-email"
main = "src/worker.ts"
compatibility_date = "2026-04-06"
compatibility_flags = [ "nodejs_compat" ] # 这个必须加，解决刚才那一堆 Error

[vars]
PREFIX = "ai"
DOMAIN = "wealthcompass.top"
ADMIN_PASS = "yoursecretpassword" # 设置一个你喜欢的管理密码

[[d1_databases]]
binding = "DB"
database_name = "temp-email"
database_id = "25891bb3-e9c9-4675-9cca-f330dfb49f5b" 

